// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BalanceSheet: typeof import('./components/widgets/BalanceSheet.vue')['default']
    Calendar: typeof import('./components/widgets/Calendar.vue')['default']
    CashFlows: typeof import('./components/widgets/CashFlows.vue')['default']
    ClassModel: typeof import('./components/widgets/ClassModel.vue')['default']
    Document: typeof import('./components/widgets/Document.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTree: typeof import('element-plus/es')['ElTree']
    FormArray: typeof import('./components/widgets/controls/FormArray.vue')['default']
    Image: typeof import('./components/widgets/controls/Image.vue')['default']
    IncomeStatement: typeof import('./components/widgets/IncomeStatement.vue')['default']
    Json: typeof import('./components/widgets/controls/Json.vue')['default']
    Layout: typeof import('./components/Layout.vue')['default']
    MainPage: typeof import('./components/MainPage.vue')['default']
    MaterializedView: typeof import('./components/widgets/simpleJson/MaterializedView.vue')['default']
    MergedAncestorsForm: typeof import('./components/widgets/MergedAncestorsForm.vue')['default']
    NestedObject: typeof import('./components/widgets/controls/NestedObject.vue')['default']
    Number: typeof import('./components/widgets/controls/Number.vue')['default']
    Page: typeof import('./components/Page.vue')['default']
    PageEditor: typeof import('./components/widgets/PageEditor.vue')['default']
    ProcessModel: typeof import('./components/widgets/ProcessModel.vue')['default']
    Raw: typeof import('./components/widgets/simpleJson/Raw.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectArrayEnum: typeof import('./components/widgets/controls/SelectArrayEnum.vue')['default']
    SelectArrayQuery: typeof import('./components/widgets/controls/SelectArrayQuery.vue')['default']
    SelectStringEnum: typeof import('./components/widgets/controls/SelectStringEnum.vue')['default']
    SelectStringQuery: typeof import('./components/widgets/controls/SelectStringQuery.vue')['default']
    SettingsDlg: typeof import('./components/SettingsDlg.vue')['default']
    StudioLayout: typeof import('./components/StudioLayout.vue')['default']
    SubForm: typeof import('./components/widgets/controls/SubForm.vue')['default']
    SubTable: typeof import('./components/widgets/controls/SubTable.vue')['default']
    TableArray: typeof import('./components/widgets/controls/TableArray.vue')['default']
    Tiptap: typeof import('./components/widgets/Tiptap.vue')['default']
    TiptapEditor: typeof import('./components/widgets/controls/TiptapEditor.vue')['default']
    ToolbarButton: typeof import('./components/widgets/ToolbarButton.vue')['default']
    Tree: typeof import('./components/widgets/Tree.vue')['default']
    Validate: typeof import('./components/widgets/simpleJson/Validate.vue')['default']
    ViewForm: typeof import('./components/widgets/ViewForm.vue')['default']
    ViewTable: typeof import('./components/widgets/ViewTable.vue')['default']
  }
}

export {}
